name: ssa_keystore
description: A command-line tool to manage keystore files for android apps.
version: 0.0.1

environment:
  sdk: ">=3.2.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  args: ^2.4.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

executables:
  ssa_keystore:
